export enum HTMLBlockTypes {
  Html = 'html',
  Head = 'head',
  Meta = 'meta',
  Title = 'title',
  Link = 'link',
  Script = 'script',
  Body = 'body',
  Div = 'div',
  Section = 'section',
  Article = 'article',
  Header = 'header',
  Footer = 'footer',
  Nav = 'nav',
  P = 'p',
  Blockquote = 'blockquote',
  Pre = 'pre',
  Address = 'address',
  Hr = 'hr',
  Ul = 'ul',
  Ol = 'ol',
  Li = 'li',
  Dl = 'dl',
  Dt = 'dt',
  Dd = 'dd',
  A = 'a',
  Button = 'button',
  Form = 'form',
  Fieldset = 'fieldset',
  Legend = 'legend',
  Label = 'label',
  Input = 'input',
  Textarea = 'textarea',
  Select = 'select',
  Option = 'option',
  Figure = 'figure',
  Figcaption = 'figcaption',
  Video = 'video',
  Audio = 'audio',
  Embed = 'embed',
  Object = 'object',
  Iframe = 'iframe',
}

export enum CSSBlockTypes {
  Display = 'display',
}
