export enum HTMLBlockTypes {
  DoctypeHTML = 'DoctypeHTML',
  Html = 'html',
  Head = 'head',
  Body = 'body',
  Meta = 'meta',
  Title = 'title',
  Style = 'style',
  Div = 'div',
  Section = 'section',
  Article = 'article',
  Header = 'header',
  Footer = 'footer',
  Nav = 'nav',
  P = 'p',
  Blockquote = 'blockquote',
  Hr = 'hr',
  Ul = 'ul',
  Ol = 'ol',
  Li = 'li',
  Dl = 'dl',
  Dt = 'dt',
  Dd = 'dd',
  A = 'a',
  Button = 'button',
  Form = 'form',
  Fieldset = 'fieldset',
  Legend = 'legend',
  Label = 'label',
  Input = 'input',
  Textarea = 'textarea',
  Select = 'select',
  Option = 'option',
  Video = 'video',
  Source = 'source',
  Audio = 'audio',
  Img = 'img',
}

export enum CSSBlockTypes {
  FontFamily = 'font-family',
  FontSize = 'font-size',
  FontWeight = 'font-weight',
  FontStyle = 'font-style',
  TextAlign = 'text-align',
  TextDecoration = 'text-decoration',
  TextTransform = 'text-transform',
  LineHeight = 'line-height',
  LetterSpacing = 'letter-spacing',
  WordSpacing = 'word-spacing',
  Color = 'color',
  ColorPicker = 'colorPicker',
  Width = 'width',
  Height = 'height',
  Margin = 'margin',
  Padding = 'padding',
  Border = 'border',
  BoxSizing = 'box-sizing',
  BorderWidth = 'border-width',
  BorderStyle = 'border-style',
  BorderColor = 'border-color',
  BorderColorPicker = 'border-color-picker',
  BorderRadius = 'border-radius',
  BackgroundColor = 'background-color',
  BackgroundColorPicker = 'background-color-picker',
  BackgroundImage = 'background-image',
  BackgroundSize = 'background-size',
  BackgroundRepeat = 'background-repeat',
  BackgroundPosition = 'background-position',
  BackgroundAttachment = 'background-attachment',
  Display = 'display',
  Position = 'position',
  Top = 'top',
  Bottom = 'bottom',
  Left = 'left',
  Right = 'right',
  ZIndex = 'z-index',
  Flex = 'flex',
  FlexDirection = 'flex-direction',
  JustifyContent = 'justify-content',
  AlignItems = 'align-items',
  GridTemplateColumns = 'grid-template-columns',
  GridTemplateRows = 'grid-template-rows',
  GridGap = 'grid-gap',
  Transition = 'transition',
  TransitionProperty = 'transition-property',
  TransitionDuration = 'transition-duration',
  TransitionTimingFunction = 'transition-timing-function',
  Animation = 'animation',
  AnimationName = 'animation-name',
  AnimationDuration = 'animation-duration',
  AnimationTimingFunction = 'animation-timing-function',
}

export enum EctBlockTypes {
  Class = 'class',
  Id = 'id',
  TextBlock = 'textBlock',
  ClassCss = 'classCss',
  IdCss = 'idCss',
  Css = 'css',
}

export default {
  HTMLBlockTypes,
  CSSBlockTypes,
  EctBlockTypes,
};
